spring:
  application:
    name: microservice-producer
    
    
server:
  port: 8001
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
  
  instance:
    hostname: localhost